In [1]:
import torch
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.9657, 0.1442, 0.3834, 0.2086, 0.3723, 0.0243, 0.0974],
        [0.2394, 0.8538, 0.2602, 0.6847, 0.3506, 0.7884, 0.3740],
        [0.1814, 0.0466, 0.7799, 0.4148, 0.3300, 0.5440, 0.9934],
        [0.6286, 0.7707, 0.2193, 0.7719, 0.7439, 0.2889, 0.6811],
        [0.0084, 0.5248, 0.9488, 0.2108, 0.7456, 0.0107, 0.3681],
        [0.3921, 0.5005, 0.0907, 0.3877, 0.5075, 0.0100, 0.6979],
        [0.4082, 0.2138, 0.2083, 0.2673, 0.6930, 0.4507, 0.2419]])

In [2]:
another_random_tensor = torch.rand(1,7)
another_random_tensor

tensor([[0.5623, 0.5687, 0.4437, 0.7348, 0.5329, 0.8121, 0.1551]])

In [3]:
torch.mm(random_tensor,another_random_tensor.T)

tensor([[1.1817],
        [2.1240],
        [1.5511],
        [2.1931],
        [1.3423],
        [1.2170],
        [1.4128]])

In [6]:
torch.manual_seed(0)

random_tensor = torch.rand(7,7)
another_random_tensor = torch.rand(1,7)
torch.mm(random_tensor,another_random_tensor.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [7]:
torch.manual_seed(1234)
tensor_1 = torch.rand(2,3)
tensor_2 = torch.rand(2,3)
print(tensor_1,tensor_2)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


In [8]:
torch.mm(tensor_1,tensor_2.T)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

In [9]:
tensor = torch.mm(tensor_1,tensor_2.T)
print(tensor.min(),tensor.max())

tensor(0.3647) tensor(0.5617)


In [10]:
print(tensor.argmax(),tensor.argmin())

tensor(3) tensor(0)


In [16]:
torch.manual_seed(7)

random_tensor = torch.rand(1,1,1,10)
squeezed = random_tensor.squeeze()
print(random_tensor,random_tensor.shape)
print(squeezed,squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
